### ISSUE TITLE
Cygwin install instructions are invalid

### ISSUE THREAD

**Issue by Stuffbutts** [mviereck/runx#1]
Great script! I've noted that your install instructions for cygwin point to the wrong url for getting the runx script.

You have:
```
wget https://github.com/mviereck/runx/blob/master/runx -O /usr/local/bin/runx
chmod +x /usr/local/bin/runx
```

When it should be:
```
wget https://raw.githubusercontent.com/mviereck/runx/master/runx -O /usr/local/bin/runx
chmod +x /usr/local/bin/runx
```

without using https://raw.githubusercontent.com/mviereck/runx/master/runx the runx scripts is just a bunch of HTML ;)

**Comment by mviereck** [comment]
Thank you!
Is fixed now. The path has been wrong in the instructions for WSL and MSYS2, too.
