### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by ghost** [mviereck/runx#3]
The copyright notice in the license file does not include the name of the copyright holder. This might lead to some confusion about attribution or the legal validity of the license statement in some jurisdictions if this script is distributed with, or incorporated in other software packages.

**Comment by mviereck** [comment]
Thank you for pointing on this!
I've added my name to the license now.

I never was sure if I have to add my name; my intention is just to publish the software as free, and the MIT licence is shortest licence I know and easy to understand.

> This might lead to some confusion about attribution or the legal validity of the license statement in some jurisdictions

Do you know an example how / where that could be an issue?

**Comment by eine** [comment]
@mviereck, AFAIK in some jurisdictions it is no allowed for a work not to have an author, where author == person. See https://en.wikipedia.org/wiki/Public_domain#Release_without_copyright_notice. Hence, it is compulsory to have a name, whenever some company needs to track who wrote each line of code that is used.

**Comment by ghost** [comment]
@mviereck
> Do you know an example how / where that could be an issue?

No i don't have any good examples that demonstrate the problem as stated. But just considering the structure of the MIT license, it directly references the author/copyright holder in the liability disclaimer, and it also requires the retransmission of the copyright notice with copies of the work.

So the license really isn't coherent without a complete copyright notice, nor could someone truly interested in compliance follow the letter of the license without it. A copyright notice's purpose is to provide written acknowledgement of who owns the right to license the work as well. So license without reference to who is providing the license feels like buying the keys to someones house in a back alley.

I am kind of rambling, and the issue has been fixed, so... yeah. Thanks for addressing this, @mviereck. I'm gonna shut up and go ahead and close.
